apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: webapp
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: imrankhan28888/kub-demo-auth:latestwebapp